# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# pipeline:
#   - name: SpacyNLP
#     # model: "en_core_web_sm"
#     model: "en_core_web_md"
#     # model: "en_core_web_lg"
#     # model: "en_core_web_trf"
#     case_sensitive: False
#   - name: SpacyTokenizer
#   - name: SpacyFeaturizer
#     "pooling": "mean"
#   - name: RegexFeaturizer
#     case_sensitive: False
#     use_word_boundaries: True
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#     lowercase: True
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#     lowercase: True
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: True
#   - name: RegexEntityExtractor
#     case_sensitive: False
#     use_lookup_tables: True
#     use_regexes: True
#   - name: FallbackClassifier
#     threshold: 0.2
#     ambiguity_threshold: 0.1
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: True  

pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
  "pooling": "mean"
- name: RegexFeaturizer
  case_sensitive: false
  use_word_boundaries: true
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
# - name: RegexEntityExtractor
#   dimensions: ["contact", "date", "time", "duration"]
#   case_sensitive: false
#   use_lookup_tables: true
#   use_regexes: true
- name: FallbackClassifier
  threshold: 0.2
  ambiguity_threshold: 0.1
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
    # use match word boundaries for lookup table
    # "use_word_boundaries": True  
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true

assistant_id: 20240912-101104-light-tail
