version: '3.4'

services:
  bot:
    container_name: rasa_bot
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: appointease:latest
    ports:
      - 5005:5005
      - 5055:5055
    env_file:
      - ./env.yml
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./models:/app/models

# networks:
#   default:
#     driver: bridge
