version: '3'

services:
  nginx-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/sharad/appointease/Chatbot-Widget/:/var/www/html
    restart: always
